import { dateNowMinusDays } from "./helpers";
import { JobPosting } from "./types";

export const JOB_LIST: JobPosting[] = [
  {
    title: 'Experienced carpenter needed for custom dog house construction',
    budget: '$300',
    dateCreated: dateNowMinusDays(4),
    description: 'Looking for a skilled construction worker to build a high-quality and weather-resistant dog house. The design should incorporate insulation and a comfortable sleeping area. Previous experience in carpentry and working with wood is required. Tools and materials will be provided.',
    experienceLevel: 'Intermediate',
    jobType: 'Fixed Price',
    postedBy: 'Adrian Albino',
  },
  {
    title: 'Emergency plumbing repair for a leaky faucet',
    budget: '$150',
    dateCreated: dateNowMinusDays(3),
    description: 'Looking for a skilled plumber to fix a leaky faucet in the kitchen. The leak is causing water wastage and needs immediate attention. Previous experience in plumbing and knowledge of faucet repair is required. Tools and replacement parts will be provided.',
    experienceLevel: 'Intermediate',
    jobType: 'Fixed Price',
    postedBy: 'Julian Camello',
  },
  {
    title: 'Seeking experienced electrician for home rewiring',
    budget: '$500',
    dateCreated: dateNowMinusDays(2),
    description: 'In need of an experienced electrician to rewire an old house. The project involves replacing outdated wiring and ensuring the electrical system meets safety standards. Previous experience in electrical work and knowledge of residential wiring is required. Materials and necessary permits will be provided.',
    experienceLevel: 'Intermediate',
    jobType: 'Fixed Price',
    postedBy: 'Ernest Adlawan',
  },
  {
    title: 'Landscaping job: Design and create a backyard garden',
    budget: '$800',
    dateCreated: dateNowMinusDays(4),
    description: 'Looking for a skilled landscaper to design and create a beautiful backyard garden. The project includes planting a variety of flowers and shrubs, installing a small pond, and building a stone pathway. Previous experience in landscaping and knowledge of plant selection and garden design is required. Tools and materials will be provided.',
    experienceLevel: 'Expert',
    jobType: 'Fixed Price',
    postedBy: 'John Doe',
  },
  {
    title: 'Painting job: Repainting a three-bedroom house',
    budget: '$1200',
    dateCreated: dateNowMinusDays(1),
    description: 'Seeking a professional painter to repaint the interior of a three-bedroom house. The project includes preparing the surfaces, applying primer and multiple coats of paint, and ensuring a clean and smooth finish. Previous experience in painting and knowledge of color selection and surface preparation is required. Paint and necessary equipment will be provided.',
    experienceLevel: 'Expert',
    jobType: 'Fixed Price',
    postedBy: 'John Doe',
  },
  {
    title: 'Hiring experienced mason for a stone patio installation',
    budget: '$1000',
    dateCreated: dateNowMinusDays(6),
    description: 'In need of an experienced mason to install a stone patio in the backyard. The project involves leveling the ground, laying the stone pavers, and creating a stable and aesthetically pleasing patio surface. Previous experience in masonry and knowledge of patio installation techniques is required. Stones and necessary tools will be provided.',
    experienceLevel: 'Intermediate',
    jobType: 'Fixed Price',
    postedBy: 'John Doe',
  },
  { 
    title: 'Need a plumber for an urgent sink fixing',
    budget: '$200',
    dateCreated: dateNowMinusDays(1),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    experienceLevel: 'Intermediate',
    jobType: 'Fixed Price',
    postedBy: 'John Doe',
  },
  { 
    title: 'Need a long time construction worker to build a dog house',
    budget: '$10',
    dateCreated: dateNowMinusDays(5),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    experienceLevel: 'Beginner',
    jobType: 'Hourly Rate',
    postedBy: 'John Doe',
  },
]